name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite escribir en el repositorio
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Mickychog # ¡Tu usuario aquí!
          outputs: |
            snake.svg
            dist/snake.svg
          palette: github-dark

      - name: Push to Branch
        uses: actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output # Rama donde se guardará el SVG
          keep_files: true # Evita borrar otros archivos
